name: dock_bounce_icon
description: "A Flutter package inspired by macOS dock bounce animation."

version: 0.0.1-beta.2
homepage: "https://github.com/mo7amedaliEbaid/bounce_icon.git"

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/sounds/heartbeat.mp3
    - assets/sounds/home.wav
    - assets/sounds/settings.wav
    - assets/images/android_studio.png
    - assets/images/figma.png
    - assets/images/xcode.png
    - assets/images/safari.png


